### ISSUE TITLE
Fail to install TabPy due to the deprecation of sklearn

### ISSUE THREAD

**Issue by AmirMK** [tableau/TabPy#578]
**Environment information:**
 - OS: Windows and Linux, Mac
 - Python version: 3.9
 - TabPy release: most recent

**Describe the issue**
Installing tabpy via pip install tabpy caused an error due to the deprecation of sklearn. The name of the library needs to change to 'scikit-learn' in tabpy dependencies

![image](https://user-images.githubusercontent.com/10812597/208975684-635042b0-558e-42b1-a0cd-9c7f3747dd57.png)

**Comment by nmannheimer** [comment]
should be fixed in latest merge!

**Comment by markvandenberg** [comment]
pypi.org/project/tabpy still has sklearn in the Requires. I'm still getting the error.
